function foo() -> i32;
start() {
    loop foo();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
global _main
_main:
; BB2:
lb8:
    jmp     lb9
; BB3:
lb9:
    call    _apl_foo0
    jmp     lb8
; BB4:
lb10:
    mov     rax, 60
    syscall
/: