function foo() -> i32;
start() {
    loop foo();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
global _main
_main:
push rbp
mov rbp, rsp
; BB5:
; BB2:
lb10:
jmp lb11
; BB3:
lb11:
call _apl_foo0
jmp lb10
; BB4:
lb12:
/: