@[naked]
function foo() -> i8 {
    return 1;
}

function bar() -> i8 {
    return 1;
}

start() {
    return foo() + bar();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
_apl_bar1:
push rbp
mov rbp, rsp
mov al, 1
mov rsp, rbp
pop rbp
ret
; BB6:
_apl_foo0:
mov al, 1
ret
; BB4:
global _main
_main:
push rbp
mov rbp, rsp
call _apl_foo0
mov dl, al
call _apl_bar1
mov bl, al
mov al, dl
add al, bl
mov sil, al
mov al, sil
mov rsp, rbp
pop rbp
ret
; BB8:
/: