@[naked]
function foo() -> i8 {
    return 1;
}

function bar() -> i8 {
    return 1;
}

start() {
    return foo() + bar();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
_apl_bar1:
push rbp
mov rbp, rsp
mov al, 1
mov rsp, rbp
pop rbp
ret
; BB6:
_apl_foo0:
mov al, 1
ret
; BB4:
global _main
_main:
push rbp
mov rbp, rsp
push rax
call _apl_foo0
pop rax
mov cl, al
push rax
call _apl_bar1
pop rax
mov dl, al
mov al, cl
add al, dl
mov bl, al
mov al, bl
mov rsp, rbp
pop rbp
ret
; BB8:
/: