@[naked]
function foo() -> i8 {
    return 1;
}

function bar() -> i8 {
    return 1;
}

start() {
    return foo() + bar();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
_apl_bar1:
    mov     al, 1
    ret
; BB6:
    ret
_apl_foo0:
    mov     al, 1
    ret
; BB4:
    ret
global _main
_main:
    call    _apl_foo0
    mov     dl, al
    call    _apl_bar1
    mov     bl, al
    mov     al, dl
    add     al, bl
    mov     cl, al
    mov     al, cl
    ret
; BB8:
    mov     rax, 60
    syscall
/: