function putc(i8 c) -> i0 {
    syscall(0x2000004, 1, ref c, 1);
}

function foo() -> i0 {
    putc('G');
}

function bar() -> i0 {
    function foo() -> i0 {
        putc('L');
    }
    foo();
}

start() {
    bar();
    foo();
    exit 0;
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
_apl_foo1:
push rbp
mov rbp, rsp
push rdi
mov dil, 71
call _apl_putc0
pop rdi
mov rsp, rbp
pop rbp
ret
global _main
_main:
push rbp
mov rbp, rsp
call _apl_bar2
push rdi
call _apl_foo1
pop rdi
mov dil, 0
mov rax, 0x2000001
syscall
; BB11:
_apl_putc0:
push rbp
mov rbp, rsp
sub rsp, 8
mov r15b, dil
mov byte [rbp - 8], r15b
lea rdx, [rbp - 8]
mov rax, 33554436
push rdi
mov rdi, 1
push rsi
mov rsi, rdx
push rdx
mov rdx, 1
push rcx
push r11
syscall
pop r11
pop rcx
pop rdx
pop rsi
pop rdi
mov rsp, rbp
pop rbp
ret
_apl_foo3:
push rbp
mov rbp, rsp
push rdi
mov dil, 76
call _apl_putc0
pop rdi
mov rsp, rbp
pop rbp
ret
_apl_bar2:
push rbp
mov rbp, rsp
jmp lb47
; BB8:
lb47:
call _apl_foo3
mov rsp, rbp
pop rbp
ret
/: