#include <asm/asmgen.h>

int ASM_generate(lir_ctx_t* lctx, asm_gen_t* g, FILE* output) {
    fprintf(output, "; Compiled .asm file. File generated by AdyCompiler!\n");
    g->declarator(lctx, output);
    g->generator(lctx, output);
    return 1;
}
