start() {
    i32 a = 10;
    exit a as i8;
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
%line 1 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 1 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
section .text
global _main
_main:
push rbp
mov rbp, rsp
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 2 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
mov ecx, 10
mov ecx, ecx
%line 3 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 3 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
%line 3 "/Users/Noah/Documents/Repositories/AdyCompiler/tests/code_utesting/asm/debug/simple.apl"
mov cl, cl
mov dil, cl
mov rax, 0x2000001
syscall
; BB2:
/: