start() {
    lis;
    lis "Coos Bay";
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .text
global _main
_main:
    int3    ;
    int3    ; Coos Bay
    mov     rax, 60
    syscall
/: