@[section(".chloe")] function foo() { return 1; }
@[section(".max")] function bar() { return 2; }
start() {
    exit foo() + bar();
}

:/ OUTPUT
; Compiled .asm file. File generated by AdyCompiler!
section .chloe
_apl_foo0:
push rbp
mov rbp, rsp
mov al, 1
mov rsp, rbp
pop rbp
ret
; BB4:
section .text
global _main
_main:
push rbp
mov rbp, rsp
call _apl_foo0
mov rdx, rax
call _apl_bar1
mov rbx, rax
mov rax, rdx
add rax, rbx
mov rdi, rax
mov rdx, rdi
mov rax, 0x2000001
syscall
; BB8:
section .max
_apl_bar1:
push rbp
mov rbp, rsp
mov al, 2
mov rsp, rbp
pop rbp
ret
; BB6:
/: