# fish completion for aplc.

complete -c aplc -s h -l help -d "Show this help message"
complete -c aplc -s v -l version -d "Show compiler version"
complete -c aplc -s s -l smth -d "Show something"
complete -c aplc -s E -d "Run preprocessor only"
complete -c aplc -s I -r -a "(__fish_complete_directories)" -d "Add include directory"
complete -c aplc -s D -r -d "Define preprocessor variable"
complete -c aplc -l print-stdlib-path -d "Print the standard library directory"
complete -c aplc -l output -r -F -d "Set output file"
complete -c aplc -l ast-analysis -d "Enable AST analysis"
complete -c aplc -l ir-analysis -d "Enable IR analysis"
complete -c aplc -l analysis-only -d "Run AST and HIR analysis, then stop before code generation"
complete -c aplc -l debug -d "Enable debug mode"
complete -c aplc -l no-debug -d "Disable debug mode"
complete -c aplc -l i-know-what-i-am-doing -d "Keep compiling after static analysis warnings"
complete -c aplc -o O0 -d "Disable optimizations"
complete -c aplc -o O1 -d "Rough optimization level"
complete -c aplc -o O2 -d "Good optimization level"
complete -c aplc -o O3 -d "Maximum optimization level"
complete -c aplc -l arch -r -a "x86_64 amd64 x86 i386 ia32" -d "Set target architecture"
complete -c aplc -l asm-compiler -r -F -d "Set assembler compiler"
complete -c aplc -l asm-format -r -a "macho64 elf64 elf32 win64" -d "Set assembler format"
complete -c aplc -l linker -r -F -d "Set linker"
complete -c aplc -l linker-mode -r -a "c driver raw ld" -d "Set linker mode"
complete -c aplc -o Xlinker -r -d "Pass one raw argument to the linker command"
complete -c aplc -l linker-arg -r -d "Pass one raw argument to the linker command"
complete -c aplc -s c -l compile-only -d "Build an object file and skip linking"
complete -c aplc -l linker-no-pie -d "Disable PIE"
complete -c aplc -l linker-pie -d "Enable PIE"
complete -c aplc -l linker-m32 -d "Enable m32 mode"
complete -c aplc -l linker-no-m32 -d "Disable m32 mode"
complete -c aplc -l entry-name -r -d "Set entry symbol name"
complete -c aplc -l ro-section -r -d "Set read-only section name"
complete -c aplc -l glob-section -r -d "Set global section name"
complete -c aplc -l code-section -r -d "Set code section name"
complete -c aplc -l full-bytness -r -a "1 2 4 8" -d "Set full bytness"
complete -c aplc -l half-bytness -r -a "1 2 4 8" -d "Set half bytness"
complete -c aplc -l quart-bytness -r -a "1 2 4 8" -d "Set quart bytness"
complete -c aplc -l eight-bytness -r -a "1 2 4 8" -d "Set eight bytness"
complete -c aplc -l sys-type -r -a "unknown macho64 linux64 i386 windows64" -d "Set system type"
complete -c aplc -l tre -d "Enable TRE"
complete -c aplc -l no-tre -d "Disable TRE"
complete -c aplc -l finline -d "Enable function inlining"
complete -c aplc -l no-finline -d "Disable function inlining"
complete -c aplc -l licm -d "Enable LICM"
complete -c aplc -l no-licm -d "Disable LICM"
complete -c aplc -l constant -d "Enable constant propagation/folding"
complete -c aplc -l no-constant -d "Disable constant propagation/folding"
complete -c aplc -l copyprop -d "Enable LIR copy propagation"
complete -c aplc -l no-copyprop -d "Disable LIR copy propagation"
complete -c aplc -l peephole -d "Enable peephole optimization"
complete -c aplc -l no-peephole -d "Disable peephole optimization"
complete -c aplc -l emit-ast -d "Emit AST dump"
complete -c aplc -l emit-ir -d "Emit HIR dump"
complete -c aplc -l emit-hir-cfg -r -d "Emit HIR CFG dump for function"
complete -c aplc -l emit-lir -d "Emit LIR dump"
complete -c aplc -l emit-lir-cfg -r -d "Emit LIR CFG dump for function"
complete -c aplc -l emit-asm -d "Emit produced assembly code"
complete -c aplc -l ast-output -r -F -d "Set AST dump output path"
complete -c aplc -l ir-output -r -F -d "Set HIR dump output path"
complete -c aplc -l lir-output -r -F -d "Set LIR dump output path"
complete -c aplc -l asm-output -r -F -d "Set assembly output path"
complete -c aplc -s L -r -a "(__fish_complete_directories)" -d "Add linker library search directory"
complete -c aplc -s l -r -d "Link library"
complete -c aplc -o Wl, -r -d "Pass comma-separated arguments to the linker"
